### ISSUE TITLE
Migrate PhpUnit to Hacktest methods that start with `should` instead of `test`.

### ISSUE THREAD

**Issue by Danon** [hhvm/hacktest#61]
My all tests in PhpUnit start with `should` instead of `test`, and they also have `@test` annotation.

Is there a way I can use your `migrate` tool?

**Comment by fredemmott** [comment]
It would probably be easiest to use `sed` or IDE global find-and-replace to replace 'function should' with 'function test', then use the migration tool

**Comment by Danon** [comment]
Yea, you night not believe, but I've already thought about that.

So, your answer is no?

**Comment by fredemmott** [comment]
No, the migration does not currently support this.

Feel free to file an issue or send a pull request over at https://github.com/hhvm/hhast to add support for renaming `@test` methods to start with `test`
